// packages/beacon-ui/src/components/wallets/index.tsx
import React from "react";
import { MergedWallet } from "../../utils/wallets";
import Wallet from "../wallet";
import "./styles.css";

interface WalletProps {
  wallets: MergedWallet[];
  onClickWallet: (id: string) => void;
  onClickOther: () => void;
  isMobile: boolean;
  small?: boolean;
  disabled?: boolean;
}

const Wallets: React.FC<WalletProps> = (props: WalletProps) => {
  return (
    <div className="wallets-list-main-wrapper">
      <div className="wallets-list-wrapper">
        {props.wallets.map((wallet) => (
          <Wallet
            key={wallet.id}
            disabled={props.disabled}
            name={wallet.name}
            description={wallet.descriptions.join(" & ")}
            image={wallet.image}
            small={props.small}
            onClick={() => props.onClickWallet(wallet.id)}
          />
        ))}
      </div>
      <button className="wallets-button" onClick={props.onClickOther}>
        {props.isMobile ? "Pair wallet on another device" : "Show QR code"}
      </button>
    </div>
  );
};


export default Wallets;

// packages/beacon-ui-solid/src/components/wallets/index.tsx
import { Component, For } from 'solid-js'
import Wallet from '../wallet'
import styles from './styles.css'

interface WalletProps {
  wallets: { name: string; description?: string; image: string }[]
}

const Wallets: Component<WalletProps> = (props: WalletProps) => {
  return (
    <div>
      <div class="wallets-list-wrapper">
        <For each={props.wallets}>
          {(wallet) => (
            <Wallet
              name={wallet.name}
              description={wallet.description}
              image={wallet.image}
              small
            />
          )}
        </For>
      </div>
      <button class="wallets-button">Pair wallet on another device</button>
    </div>
  )
}

export { styles }
export default Wallets
